apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: despacho-app
  labels:
    app: backend-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 548946983683.dkr.ecr.us-east-1.amazonaws.com/backend-ventas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: despachos
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: JAVA_OPTS
              value: "-XX:+UseG1GC"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas
  namespace: despacho-app
spec:
  selector:
    app: backend-ventas
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
