apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CAMBIAR_PASSWORD"
  SPRING_DATASOURCE_USERNAME: "CAMBIAR_USUARIO"
  SPRING_DATASOURCE_PASSWORD: "CAMBIAR_PASSWORD"