name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - devops

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: innovatech

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Obtener URLs ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          echo "FRONTEND_ECR=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-frontend" >> $GITHUB_ENV
          echo "VENTAS_ECR=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-ventas" >> $GITHUB_ENV
          echo "DESPACHOS_ECR=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-despachos" >> $GITHUB_ENV

      - name: Build Backend Ventas
        run: |
          docker build \
            -t $VENTAS_ECR:${GITHUB_SHA} \
            -t $VENTAS_ECR:latest \
            ./backend/back-Ventas_SpringBoot/Springboot-API-REST

      - name: Push Backend Ventas
        run: |
          docker push $VENTAS_ECR:${GITHUB_SHA}
          docker push $VENTAS_ECR:latest

      - name: Build Backend Despachos
        run: |
          docker build \
            -t $DESPACHOS_ECR:${GITHUB_SHA} \
            -t $DESPACHOS_ECR:latest \
            ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO

      - name: Push Backend Despachos
        run: |
          docker push $DESPACHOS_ECR:${GITHUB_SHA}
          docker push $DESPACHOS_ECR:latest

      - name: Build Frontend
        run: |
          docker build \
            -t $FRONTEND_ECR:${GITHUB_SHA} \
            -t $FRONTEND_ECR:latest \
            ./front_despacho

      - name: Push Frontend
        run: |
          docker push $FRONTEND_ECR:${GITHUB_SHA}
          docker push $FRONTEND_ECR:latest